import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { fetchApplicantById } from '../services/api';
import { Printer, ArrowLeft, Download, FileText } from 'lucide-react';

const ApplicantDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [applicant, setApplicant] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getApplicant = async () => {
      try {
        const { data } = await fetchApplicantById(id);
        setApplicant(data);
      } catch (error) {
        console.error('Error fetching applicant:', error);
      } finally {
        setLoading(false);
      }
    };
    getApplicant();
  }, [id]);

  if (loading) return <div className="text-center py-20">Loading details...</div>;
  if (!applicant) return <div className="text-center py-20 text-red-500">Applicant not found</div>;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 print:m-0 print:p-0">
      {/* Action Buttons - Hidden during print */}
      <div className="flex justify-between items-center print:hidden">
        <button onClick={() => navigate(-1)} className="flex items-center text-gray-600 hover:text-indigo-600 transition-colors">
          <ArrowLeft className="mr-2 h-5 w-5" /> Back to List
        </button>
        <button
          onClick={handlePrint}
          className="bg-indigo-600 text-white px-6 py-2.5 rounded-xl flex items-center hover:bg-indigo-700 transition-all shadow-md"
        >
          <Printer className="mr-2 h-5 w-5" /> Print / Export PDF
        </button>
      </div>

      {/* Profile Card / Print Layout */}
      <div className="bg-white rounded-3xl shadow-sm border overflow-hidden print:shadow-none print:border-0 print:rounded-none">
        {/* Header Section */}
        <div className="bg-slate-900 text-white p-8 md:p-12 flex justify-between items-end print:bg-white print:text-slate-900 print:border-b-2 print:border-slate-200 print:px-0">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold">{applicant.firstName} {applicant.lastName}</h1>
            <p className="text-indigo-300 font-medium text-lg print:text-indigo-600">{applicant.department?.name}</p>
          </div>
          <div className="text-right space-y-1">
            <div className={`px-4 py-1.5 rounded-full text-sm font-bold inline-block ${getStatusStyle(applicant.status)}`}>
              {applicant.status}
            </div>
            <p className="text-slate-400 text-sm print:text-slate-500">Applied: {new Date(applicant.createdAt).toLocaleDateString()}</p>
          </div>
        </div>

        {/* Content Section */}
        <div className="p-8 md:p-12 space-y-12 print:px-0">
          {/* Grid Information */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <section className="space-y-6">
              <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest border-b pb-2">Contact Information</h3>
              <div className="space-y-4">
                <InfoItem label="Email" value={applicant.email} />
                <InfoItem label="Phone" value={applicant.phone} />
              </div>
            </section>
            <section className="space-y-6">
              <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest border-b pb-2">Application Details</h3>
              <div className="space-y-4">
                <InfoItem label="Department" value={applicant.department?.name} />
                <InfoItem label="ID" value={applicant._id} />
              </div>
            </section>
          </div>

          {/* Files Section - Hidden during print if you only want data, or keep it if it's a summary */}
          <section className="space-y-6 print:hidden">
            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest border-b pb-2">Attached Documents</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <FileCard label="Resume" path={applicant.resume} />
              <FileCard label="Transcript" path={applicant.transcript} />
            </div>
          </section>

          {/* Print Only Footer */}
          <div className="hidden print:block pt-20 text-center text-slate-400 text-xs italic">
            Generated by Recruitment Management System - {new Date().toLocaleString()}
          </div>
        </div>
      </div>
    </div>
  );
};

const InfoItem = ({ label, value }) => (
  <div>
    <p className="text-xs font-semibold text-gray-500 uppercase">{label}</p>
    <p className="text-lg text-gray-900 font-medium">{value || 'N/A'}</p>
  </div>
);

const FileCard = ({ label, path }) => {
  const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
  
  // Clean the BASE_URL by removing /api if present at the end
  const serverUrl = BASE_URL.replace(/\/api$/, '');
  
  // Logic to determine the final URL:
  // 1. If path is already a full URL (starts with http), use it.
  // 2. If it's a relative path (filename only), prefix it with serverUrl/uploads/
  const finalUrl = path?.startsWith('http') 
    ? path 
    : `${serverUrl}/uploads/${path}`;

  return (
    <div className={`flex items-center justify-between p-4 border-2 rounded-2xl transition-all ${path ? 'border-gray-100 bg-gray-50 hover:border-indigo-200' : 'border-dashed border-gray-200 opacity-50'}`}>
      <div className="flex items-center space-x-3">
        <div className={`p-2 rounded-lg ${path ? 'bg-indigo-100 text-indigo-600' : 'bg-gray-100 text-gray-400'}`}>
          <FileText className="h-6 w-6" />
        </div>
        <span className="font-bold text-gray-800">{label}</span>
      </div>
      {path && (
        <a
          href={finalUrl}
          target="_blank"
          rel="noreferrer"
          className="text-indigo-600 hover:text-indigo-800"
        >
          <Download className="h-5 w-5" />
        </a>
      )}
    </div>
  );
};

const getStatusStyle = (status) => {
  switch (status) {
    case 'Accepted': return 'bg-green-500/20 text-green-400 print:bg-green-100 print:text-green-700';
    case 'Rejected': return 'bg-red-500/20 text-red-400 print:bg-red-100 print:text-red-700';
    case 'Interviewing': return 'bg-purple-500/20 text-purple-400 print:bg-purple-100 print:text-purple-700';
    case 'Reviewing': return 'bg-blue-500/20 text-blue-400 print:bg-blue-100 print:text-blue-700';
    default: return 'bg-slate-500/20 text-slate-400 print:bg-slate-100 print:text-slate-700';
  }
};

export default ApplicantDetails;
